---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - common

- hosts: ruby-dev
  become: yes
  become_method: sudo
  roles:
    - ruby-dev

- hosts: go-dev
  become: yes
  become_method: sudo
  roles:
    - go-dev

- hosts: ansible
  become: yes
  become_method: sudo
  roles:
    - ansible


- hosts: database
  become: yes
  become_method: sudo
  roles:
    - mysql
    - postgresql

