---
- name: Install packages
  apt: name={{ item }} install_recommends=no
  with_items:
    - python-setuptools
    - devscripts
    - fakeroot
    - asciidoc
    - cdbs
    - debhelper
    - python-support
    - python-jinja2
    - python-yaml
    - python-paramiko
    - python-httplib2
    - python-crypto
    - sshpass

- name: Download Ansible
  get_url:
    url=https://github.com/ansible/ansible/archive/v1.9.4-1.tar.gz
    dest=~/ansible.tar.gz
    mode=0440

- name: Create & ansible .deb
  shell: tar zxvf ~/ansible.tar.gz && cd ansible-1.9.4-1 && make deb && dpkg -i ./deb-build/unstable/ansible_*.deb

- name: Remove extracted archive
  file: path=ansible-1.9.4-1 state=absent

- name: Remove archive
  file: path=~/ansible.tar.gz state=absent

