---
- name: Install packages
  apt: name={{ item }} install_recommends=no
  with_items:
    - python-setuptools
    - python-support
    - python-jinja2
    - python-yaml
    - python-paramiko
    - python-httplib2
    - python-crypto
    - sshpass

- name: Download Ansible
  get_url:
    url=https://github.com/ansible/ansible/archive/v1.9.4-1.tar.gz
    dest=/tmp/ansible.tar.gz
    mode=0440

- name: Extract ansible.tar.gz
  unarchive:
    src=/tmp/ansible.tar.gz
    dest=/tmp
    copy=no
    creates=/tmp/ansible-1.9.4-1

- name: Install Ansible
  shell: make install
    chdir=/tmp/ansible-1.9.4-1
    creates=/usr/local/bin/ansible

- name: Remove temporary directory
  file: path=/tmp/ansible-1.9.4-1 state=absent

- name: Remove archive
  file: path=/tmp/ansible.tar.gz state=absent

