---
- name: Install packages
  apt: name={{ item }} install_recommends=no
  with_items:
    - python-setuptools
    - python-support
    - python-jinja2
    - python-yaml
    - python-paramiko
    - python-httplib2
    - python-crypto
    - sshpass

- name: Clone Ansible Repo
  git:
    repo=https://github.com/ansible/ansible.git
    dest=/tmp/ansible
    clone=yes
    version=v1.9.4-1

- name: Install Ansible
  shell: make install
    chdir=/tmp/ansible
    creates=/usr/local/bin/ansible

- name: Remove temporary directory
  file: path=/tmp/ansible state=absent

