---
- name: Check if /usr/local/bin/ansible exists
  stat: path=/usr/local/bin/ansible
  register: ansiblecheck

- name: Install Ansible
  include: install.yaml
  when: ansiblecheck.stat.exists == False

